name: perturbseq-processing
channels:
- conda-forge
dependencies:
- conda-forge::r-base=4.2.2
- conda-forge::r-seurat=4.3.0
- conda-forge::r-devtools=2.4.5
- conda-forge::r-dplyr=1.0.10
- conda-forge::r-readr=2.1.3
- conda-forge::r-tibble=3.1.8
- conda-forge::jupyter=1.0.0
- conda-forge::r-irkernel=1.3.1
- conda-forge::nb_conda_kernels=2.3.1
- conda-forge::widgetsnbextension=4.0.4
- conda-forge::jupyter_contrib_nbextensions=0.7.0
