name: perturbseq-processing
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::r-base=4.0
- conda-forge::r-devtools=2.3.2
- conda-forge::r-dplyr
- conda-forge::r-readr
- conda-forge::r-tibble
- conda-forge::jupyter=1.0.0
- conda-forge::r-irkernel=1.1.1
- conda-forge::nb_conda_kernels=2.3.1
- conda-forge::widgetsnbextension=3.5.1
- conda-forge::jupyter_contrib_nbextensions=0.5.1
