name: grit-benchmark
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python
- conda-forge::pandas=1.2
- conda-forge::numpy
- conda-forge::pathlib
- conda-forge::requests
- conda-forge::jupyter
- conda-forge::jupyterlab
- conda-forge::ipykernel
- conda-forge::nb_conda_kernels
- conda-forge::widgetsnbextension
- conda-forge::jupyter_contrib_nbextensions
- conda-forge::matplotlib
- conda-forge::plotnine
- conda-forge::seaborn
- conda-forge::umap-learn
- conda-forge::black
- conda-forge::nb_black
- bioconda::mygene=3.1.0
- bioconda::phate=1.0.4
- pip:
  - git+https://github.com/cytomining/pycytominer@90fda6bc071825a526616130bd6ffe454cf17aaa
  - git+https://github.com/cytomining/cytominer-eval@3b2a44aa0097db132357d2fe90953e9d258a34d1
